openapi: 3.0.3
info:
  title: Order API
  version: 1.0.0
paths:
  /order:
    post:
      operationId: createOrder
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
      responses:
        '201':
          description: Created
  /order/{id}:
    get:
      operationId: getOrder
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
components:
  schemas:
    Order:
      type: object
      required: [name, email]
      properties:
        name:
          type: string
        email:
          type: string