openapi: 3.0.3
info:
  title: Payment API
  version: 1.0.0
paths:
  /payment:
    post:
      operationId: createPayment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Payment'
      responses:
        '201':
          description: Created
  /payment/{id}:
    get:
      operationId: getPayment
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
components:
  schemas:
    Payment:
      type: object
      required: [name, email]
      properties:
        name:
          type: string
        email:
          type: string